name: Simple CI/CD

on:
  push:
    branches:
      - main

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build
        run: echo "Build successful"

      - name: Test
        run: echo "All tests passed"

      - name: Deploy
        run: echo "Application deployed"
